# The URL the site will be built for
base_url = "https://mr-milk.cn"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
default_language = "en"
languages = [
    {code = "zh-cn"},
]


[extra]
author="Mr.Milk"
author_image="me.jpg"
city="Guang Zhou, Macau"
years="2021"

job = "Second year Ph.D. ğŸ§ğŸ“šğŸ–¥"
description = "Work on spatial single-cell"

links = [
    { url = "https://github.com/Mr-Milk", title="Mr-Milk", icon = "fab fa-github"},
    { url = "https://www.linkedin.com/in/%E6%98%93%E6%B0%91-%E9%83%91-562923160/?locale=en_US", title="Linkedin", icon = "fab fa-linkedin"},
    { url = "mailto:yb97643@um.edu.mo", title="School Email",icon = "fas fa-envelope"}
]

# if you add languages, put your emoji flag on array
languages_flags = [
    "ğŸ‡¬ğŸ‡§",
    "ğŸ‡¨ğŸ‡³",
]